# Generated by Selenium IDE
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestMytest():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_mytest(self):
        self.driver.get("https://practicetestautomation.com/practice-test-login/")
        self.driver.set_window_size(945, 578)
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-43 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-20 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-21 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, "#menu-item-43 > a").click()
        self.driver.find_element(By.ID, "form_first_name_7").click()
        self.driver.find_element(By.ID, "form_first_name_7").click()
        self.driver.find_element(By.ID, "form_first_name_7").send_keys("henitha")
        self.driver.find_element(By.ID, "form_email_7").click()
        self.driver.find_element(By.ID, "form_email_7").send_keys("christy.henitha@gmail.com")
        self.driver.find_element(By.CSS_SELECTOR, ".mailpoet_submit").click()
        self.driver.close()

